### ISSUE TITLE
Scroll to Element

### ISSUE THREAD

**Issue by drockdriod** [Trendyol/react-carousel#60]
### Clear and concise description of the problem

I believe **react-carousel** should have the ability to scroll to a specific element in a carousel.

### Suggested solution

For example, if there is five elements and I want to have element 4 visible, there should be an "initialIndex" property that would display that xth element on carousel initialization.

### Validations

- [x] Follow our [Code of Conduct](https://github.com/Trendyol/react-carousel/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Trendyol/react-carousel/blob/master/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hasangenc0** [comment]
Which component are you talking about, `Carousel` or `ScrollingCarousel` ?
Because the `Carousel` component has this ability. If you want to 4 element to be visible, you can set `show` prop to `4`. And if you want to render `nth` item in your array you should map that array first with the proper order.

**Comment by Shawn59** [comment]
I agree. The ability to select an element during initialization is very lacking
